#!/usr/bin/python

import json
from pprint import pprint
json_data=open('data/basis-2014-06-03.json')

data = json.load(json_data)
	
print "air_temp,skin_temp,calories,gsr,heart_rate,steps,posture_score"
for d in range(0,1440):
	print data['metrics']['air_temp']['values'][d],",",data['metrics']['skin_temp']['values'][d],",",data['metrics']['calories']['values'][d],",",data['metrics']['gsr']['values'][d],",",data['metrics']['heartrate']['values'][d],",",data['metrics']['steps']['values'][d]


#pprint(data['metrics']['air_temp'])
json_data.close()